Feature: adds a responsive navigation bar
rhul-compsoc/royalhackaway.com pull request #1
Opened 2020-10-10 19:16 UTC by ixahmedxi

This commit brings the following changes:

- Replaces the old navigation bar with a new one that is responsive
on mobile devices.

- Moves the MajorLeagueHackingBadge into the navigation bar component,
that way it stays relative to the navigation bar and does not overlap
the menu.

- Removes the yarn.lock file and defaults into using npm throughout the
project.

Changes to be committed:
	modified:   package-lock.json
	modified:   src/components/Header/index.js
	modified:   src/components/Header/index.module.scss
	modified:   src/components/Layout/index.js
	modified:   src/components/MajorLeagueHackingBadge/index.module.scss
	deleted:    yarn.lock

2020-10-10 21:41 UTC, 7coil commented
I'm not sure if we're going to be removing yarn, I'll take a look while I gather people's opinions

2020-10-10 21:43 UTC, ixahmedxi commented
The PR can still be merged and if a switch to yarn happens in the future than that can be done as another commit. The current version of having both a yarn.lock and a package-lock.json files is not a good option anyways.

2020-10-12 04:56 UTC, 7coil commented
According to a straw poll, 6/6 people want npm over yarn.
Although removing yarn.lock should be done, it would be better if this change was made in a separate pull request, not only to make merges more atomic (which we all love as part of Software Development), but also ~~to get that great Hacktoberfest t-shirt~~.

To do this, you can just temporarily restore yarn.lock and remove package-lock.json in an additional commit, and I'll perform a squash merge.

Then, in a separate merge request, you can delete yarn.lock and add in the package-lock.json

2020-10-12 20:08 UTC, ixahmedxi commented
Done

2020-10-13 03:44 UTC, 7coil requested changes
Use the Bootstrap SASS mixins please.

2020-10-13 03:44 UTC, 7coil commented on src/components/MajorLeagueHackingBadge/index.module.scss
> +$breakpoint-lg: 992px;
and also same here.

2020-10-13 18:47 UTC, ixahmedxi commented
I have changed the responsive media queries to bootstrap mixins, I have however chosen to not import the intire bootstrap scss and only include the parts required to make it work that way we don't import unneccessary stuff.

2020-10-13 18:49 UTC, 7coil approved these changes
Everything looks fine now, thanks a lot!

2020-10-13 18:49 UTC, merged